modLoader="javafml"

loaderVersion="${mod_loader_version}"

issueTrackerURL="${mod_issue_url}"
logoFile="${mod_icon}"

license="GPL v3.0"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''

[[dependencies.magicaljewelry]]
    modId="forge"
    mandatory=true
    versionRange="${mod_loader_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.magicaljewelry]]
    modId="minecraft"
    mandatory=true
    versionRange="${mod_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.magicaljewelry]]
    modId="curios"
    mandatory=true
    versionRange="${version_range_curios}"
    ordering="NONE"
    side="BOTH"