modLoader="javafml"

loaderVersion="[31,)"

issueTrackerURL="https://https://github.com/Erfurt92/MagicalJewelry/issues"
logoFile="${mod_icon}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''

[[dependencies.magicaljewelry]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.magicaljewelry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"