modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
modId="magicaljewelry" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Magical Jewelry" #mandatory
authors="Erfurt"
description='''
Magical Jewelry is a mod that adds rings and amulets of different rarities, with potion/beacon effects.
'''

[[dependencies.magicaljewelry]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.magicaljewelry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.magicaljewelry]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.15.2-2.0.2.1,)"
    ordering="NONE"
    side="BOTH"