modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="magicaljewelry" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Magical Jewelry" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="magicaljewelry.png" #optional

credits="Thanks for this example mod goes to Java" #optional

authors="Erfurt"

description='''

'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.magicaljewelry]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.magicaljewelry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.magicaljewelry]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.15.2-2.0.2.1,)"
    ordering="NONE"
    side="BOTH"